# this is the configuration file for the project

render_method = "polygons"
endpoint = "pygame" # pygame, terminal, file

[analysis]
debug = true   # records inputs and outputs of functions
timing = true  # times functions
logging = true # logs shit
mermaid = true # generates a mermaid diagram out of the function flow


[window]
h_res = 720 # actual endpoint size
v_res = 720
smoothscale = true
scaling = 1 # horizontal pixels that go into making a single pixel

[camera]
focal_length=20
sensor_width=10
close_cull=0.1
far_cull=1000

[scene]

[raster]
occlusion = true
weight = 1
individual = false # draws individually
# NOTICE; stalls frame if you try to smoothscale
# best practice is scaling = 1
# if on, scaling is overridden to be 1

draw_color = [0,0,0] # draw color
face_color = [255,255,255]
background = [0,0,0] # background color

[timing]
running_avg_size = 100 # the number of past timings to factor into the average
